### PR TITLE
Fix HTTP request crash when the response does not contain a `Content-Type` header.

### LINKED ISSUE #305: HTTP request library fails internally if a HTTP response does not contain a 'Content-Type' header
I am experiencing exceptions with the following stacktrace:
```
java.lang.NullPointerException: Cannot invoke method contains() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at org.dsty.http.Requests.execute(Requests.groovy:156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at org.dsty.http.Requests.get(Requests.groovy:84)
```

Given the stacktrace, I think the problematic code is indeed at
https://github.com/DontShaveTheYak/jenkins-std-lib/blob/master/src/org/dsty/http/Requests.groovy#L156
```
if (response.headers?.'Content-Type'.contains('application/json')) {
            JsonSlurperClassic slurper = new JsonSlurperClassic()
            response.json = slurper.parseText(response.body)
        }
```
which can try to call `contains` on a null object

### PR DESCRIPTION
**Pull request by alacoste**
Fixes: https://github.com/DontShaveTheYak/jenkins-std-lib/issues/305

### CODE REVIEW

File: src/org/dsty/http/Requests.groovy [hunk 1]
```diff
@@ -153,7 +153,7 @@ class Requests implements Serializable {
 
         Response response = handleRequest(connection)
 
-        if (response.headers?.'Content-Type'.contains('application/json')) {
+        if (response.headers?.'Content-Type'?.contains('application/json') == true) {
```
Comment (shadycuz) [inline src/org/dsty/http/Requests.groovy:156]: I see what I did wrong =/

**Comment by shadycuz** [comment]
I thought only I used this code 👀. I think this makes you the first contributor! <3

Thanks for the fix, I just need to do a couple of things. But will try and get this officially released soon.

**Comment by alacoste** [comment]
> I thought only I used this code 👀. I think this makes you the first contributor! <3
> 
> Thanks for the fix, I just need to do a couple of things. But will try and get this officially released soon.

Sounds good, obviously feel free to edit this PR & merge it as you see fit :)
